
// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class Input()Test {


    // bet is set to 1000 when input() is called
    @Test
    public void test_bet_is_set_to_1000() {
        Sportpesa sportpesa = new Sportpesa();
        sportpesa.input();
        assertEquals(1000, sportpesa.bet);
    }

    // input() is called multiple times consecutively
    @Test
    public void test_input_called_multiple_times() {
        Sportpesa sportpesa = new Sportpesa();
        sportpesa.input();
        sportpesa.input();
        assertEquals(1000, sportpesa.bet);
    }
}